#!/bin/bash

# сколько процессов запускать
PHP_FCGI_CHILDREN=5
# через сколько обработанных запросов перезапускать экземпляр
PHP_FCGI_MAX_REQUESTS=1000

# PHP_SCRIPT="/usr/bin/spawn-fcgi -a 127.0.0.1 -p 9000 -u www-data -g www-data -f /usr/bin/php5-cgi"

PHP_SCRIPT="/usr/bin/spawn-fcgi -s /var/run/php/fcgi -u www-data -g www-data -f /usr/bin/php5-cgi"

RETVAL=0

case "$1" in
    start)
	$PHP_SCRIPT
	RETVAL=$?
	;;
    stop)
	killall -9 php5-cgi
	RETVAL=$?
	;;
    restart)
	killall -9 php5-cgi
	$PHP_SCRIPT
	RETVAL=$?
	;;
    *)
	echo "Usage: sudo /etc/init.d/init-fastcgi {start|stop|restart}"
	exit 1
	;;
esac

exit $RETVAL